// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"chikuwa","status":true,"description":"variable store chikuwa","parameters":{"FileName":"chikuwa","WebStorageKey":"Chikuwa"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"AdjustPictureGraphical","status":true,"description":"Plugin that adjust picture to graphical","parameters":{"GridSize":"48","TestMapId":"-1"}},
{"name":"PictureCallCommon","status":true,"description":"Clickable picture plugin","parameters":{"TransparentConsideration":"ON","GameVariablePictureNum":"1"}},
{"name":"ChangeMaxLevel","status":true,"description":"最大レベルを変更します","parameters":{"newMaxLevel":"1000"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"PlayMsgWndCharSE","status":true,"description":"Play SE for each character at message window","parameters":{"default SE":"1","battle default SE":"0","interval":"2","name1":"Cursor1","volume1":"90","pitch1":"100","name2":"Cursor2","volume2":"75","pitch2":"125"}},
{"name":"PictureVariableSetting","status":true,"description":"ピクチャの変数設定プラグイン","parameters":{"初期値":"OFF"}},
{"name":"YEP_MessageCore","status":true,"description":"v1.02 Adds more features to the Message Window to customized\nthe way your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward":"Input.isPressed('pagedown')","Word Wrapping":"false","Description Wrap":"false","---Font---":"","Font Name":"GameFont","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]"}},
{"name":"111_InputForm","status":true,"description":"フォーム作って文字入力","parameters":{}},
{"name":"TDDP_PreloadManager2","status":true,"description":"1.1.1 Preload resources on scene/map load as well as game startup for a smoother gameplay experience.          id:TDDP_PreloadManager","parameters":{"Preload On Map Load":"true","Preload System Music":"false","Preload System SFX":"false","Print Debug to Console":"false"}}
];
